### ISSUE TITLE
Remove Telemetry 

### ISSUE THREAD

**Issue by ImInTheICU** [ohsunset/Snapbot#8]
Hello!
I'm not a huge fan of the hidden telemetry (sending a POST request to a Discord webhook when opened).
In it's self it is harmless.
But I have went ahead and done all of it's users a favor by deleting your webhook!
`https://discord.com/api/webhooks/1236180382517559327/5Sw56ScFA1jim0Azwaj0fQTpLvZAlTuk7BbS98IvKSw_iDpnr53HBTnVCi5j6ZA6TVyK`
OR
```
f = "1236180382517559327/"
j = "5Sw56ScFA1jim0Azwaj0fQTpLvZA"
l = "lTuk7BbS98IvKSw_iDpnr53HBTnVCi5j6ZA6TVyK"
a = "api/"
w = "webhooks/"
g = f"{j}{l}"
d = "discord.com/"
h = "https://"
u = f"{h}{d}{a}{w}{f}{g}"
print(u)
```

Otherwise noted, good project and I hope to see more from you.

**Comment by ohsunset** [comment]
im not gonna add that to the code because my friend made it. i will add a disclaimer
